# HANDS-ON 1

### Task 1: Import NumPy

In [41]:
import numpy as np
# if this runs without an error it means numpy have been successfully imported in to this environment

### Task 2: Creating An Array 

In [42]:
# Creating an array
temperature_list = [27.5, 29., 28.5]
temperature_array = np.array(temperature_list)
# printing
print(temperature_list)
print()
print(temperature_array)

[27.5, 29.0, 28.5]

[27.5 29.  28.5]


### Task 3: Inspecting The Data Type

In [43]:
print(temperature_array.dtype)
# The concept is dtype -> it tells us the data type of ALL elements in the array. 
# It's float because we have decimals.

float64


### Task 4: Creating a 2D Array 

In [44]:
# creating a 2D array
weather_data = [
    [27.5, 28.0, 29.5],
    [28.0, 29.0, 30.0]
]
weather_array = np.array(weather_data)

print(weather_array)
# My Prediction BEFORE running:
# Is this a 1D or 2D array? -> 2D array
# Is it a vector or matrix? -> Matrix (because it's a 2D array)
# How many rows? -> 2 rows (2 weather stations)
# How many values in each row? -> 3 values (3 days)

[[27.5 28.  29.5]
 [28.  29.  30. ]]


# HANDS-ON 2

### Task 1: try using python list to perform numberical operations

In [45]:
sales_timothy = [10, 15, 20]
sales_brenda = [5, 10, 15]
result = sales_timothy + sales_brenda
#print(result)
# 1. python did not perform an arithemetical option instead 
# 2. it combine the two variables together which is called a concatination
# 3. numpy arrays are much more efficient than list and to perform the operation on will take the longer procedure

### Task 2: converting it to numpy

In [46]:
sales_timothy = np.array(sales_timothy)
sales_brenda = np.array(sales_brenda)
result = sales_timothy + sales_brenda
#print(result)

### Task 3: comparing results

In [47]:
# Approach       Result
# Python lists   [10, 15, 20, 5, 10, 15] -> Concatenation
# NumPy arrays   [15 25 35]              -> Element-wise Addition

# Why is NumPy useful here?
# NumPy allows VECTORIZED, element-by-element operations. It lets me do Day1+Day1, Day2+Day2 without writing a for loop. It treats the whole array as math, not just a storage box.

### Task 5: 5 Days online  sales vs store sales

In [48]:
# Monday to Friday
online_sales = np.array([20, 35, 40, 25, 50])
store_sales = np.array([15, 30, 25, 40, 45])
# Combined sales days per day
combined_sales = online_sales + store_sales
# Defference per day (Online sales - Store sale)
defference = online_sales - store_sales
# Displaying result 
print ("Combined Sales:", combined_sales)
print ("Defference:", defference)

Combined Sales: [35 65 65 65 95]
Defference: [  5   5  15 -15   5]


# HANDS-ON 3

 ## MINI PROJECT 

### Weather Temperature Analysis with NumPy

In [49]:
# Creating a python list and Numpy array 
temperatures = [27.5, 29.0, 30.5, 28.00, 31.0, 32.5, 30.0]
temperatures_array = np.array(temperatures)
print(temperatures_array)
# Ans 1. The temperature is a 1D array
# Ans 2. It is a Vector
# Ans 3. The data type is and integer
# Counting the number in temperatures observed
temperatures_obeserved = len(temperatures)
print("Nunbers Of Temperatures Obeserved: ", temperatures_obeserved)

[27.5 29.  30.5 28.  31.  32.5 30. ]
Nunbers Of Temperatures Obeserved:  7


In [50]:
# Q1: Is it 1D or 2D?
print("Dimensions:", temperatures_array.ndim) # 1D

# Q2: Vector or Matrix?
# Answer: Vector (1D array is called a vector)

# Q3: What is its data type?
print("dtype:", temperatures_array.dtype) # float64

# Q4: How many observations?
temperatures_obeserved = len(temperatures) #7
print("Nunbers Of Temperatures Obeserved: ", temperatures_obeserved)

Dimensions: 1
dtype: float64
Nunbers Of Temperatures Obeserved:  7


In [51]:
# calculating the difference between the rocorded temperature and the targeted temperature
target = [28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0]
target_array = np.array(target)
temperature_difference = temperatures_array - target_array
# Increasing the temperature by 2 degree census
temperature_increase = (2 + temperature_difference)
# No for loop needed! NumPy broadcasts the +2 to every element.

# displaying output
print("Temperature Difference:", temperature_difference)
print()
print("Temperature Increase:", temperature_increase)

Temperature Difference: [-0.5  1.   1.5  0.   1.   2.5  1. ]

Temperature Increase: [1.5 3.  3.5 2.  3.  4.5 3. ]


##### Business Question 1 - Which day has highest temp? Day 6 has 32.5°C (Index 5). Use np.argmax(temperatures_array)
##### Business Question 2 - Days above target? Days where diff > 0 -> Day 2, 3, 5, 6, 7
##### Business Question 3 - What does difference tell? Positive means we were hotter than expected, negative means cooler. Helps weather team track forecast accuracy.
##### Business Question 4 - Why NumPy is better? With list I'd need loops for list - target or +2. With NumPy it's one line, cleaner and faster for analysis.

# MINI PROJECT CHALLENGE

In [52]:
# creating Python list and Numpy array for three location
lagos = [27.5, 29.0, 30.5, 28.0, 30.0]
abuja = [25.0, 28.0, 29.0, 27.5, 30.5]
ibadan = [26.5, 28.5, 29.0, 27.5, 30.5]

lagos_array = np.array(lagos)
abuja_array = np.array(abuja)
ibadan_array = np.array(ibadan)

# Stack into a 2D array for easier multi-location analysis (shape: 3 locations x 5 days)
all_locations = np.array([lagos, abuja, ibadan])
locations = ["Lagos", "Abuja", "Ibadan"]
# Displaying output
print("Lagos Temperature:", lagos_array)
print("Abuja Temperature:", abuja_array)
print("Ibadan Temperature:", ibadan_array)

Lagos Temperature: [27.5 29.  30.5 28.  30. ]
Abuja Temperature: [25.  28.  29.  27.5 30.5]
Ibadan Temperature: [26.5 28.5 29.  27.5 30.5]


In [53]:
# Which location recorded the highest temperature on each day
max_indices_per_day = np.argmax(all_locations, axis=0)
highest_location_per_day = [locations[idx] for idx in max_indices_per_day]

print("Daily max location:", highest_location_per_day)

Daily max location: ['Lagos', 'Lagos', 'Lagos', 'Lagos', 'Abuja']


In [54]:
# Increasing every recorded temperature by 1 degree census
all_plus_1 = all_locations + 1
print("All locations (+1°C):\n", all_plus_1)

All locations (+1°C):
 [[28.5 30.  31.5 29.  31. ]
 [26.  29.  30.  28.5 31.5]
 [27.5 29.5 30.  28.5 31.5]]


In [55]:
# Comparing Lagos temperatures with Abuja temperatures
temperature_difference = lagos_array - abuja_array
print("Difference (Lagos - Abuja):", temperature_difference)


Difference (Lagos - Abuja): [ 2.5  1.   1.5  0.5 -0.5]


In [56]:
# Question: Explain why NumPy becomes increasingly useful as the amount of numerical data grows.

# Answers:
# 1. Vectorized Operations: Eliminates explicit Python for loops, enabling operations across large datasets simultaneously with concise code[cite: 1].

# 2. Performance & Speed: NumPy array operations are significantly faster than plain Python lists.

# 3. Multidimensional Handling: Simplifies complex calculations across multiple rows, columns, or dimensions (e.g., comparing weather across many cities or years) using structured slicing and aggregation functions[cite: 1].